### ISSUE TITLE
`lein run-client` gives "Unsupported major.minor version 51.0"

### ISSUE THREAD

**Issue by r00k** [bellkev/dacom#5]
```
noodle% lein run-client 
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/eclipse/jetty/server/Handler : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
```

**Comment by r00k** [comment]
Please let me know what other info I can provide to help diagnose this. Thanks!

**Comment by bellkev** [comment]
I'm guessing this is because lein-httpd (which is the simple little webserver I included to serve up static files in the dev profile) uses Jetty 9, which requires Java 1.7 (a.k.a. 51.0).

Are you using Java 1.7? If not, you can either switch to Java 1.7 or use some other dev web server.

**Comment by dviramontes** [comment]
installing java 1.7 helped. Thanks!

**Comment by bellkev** [comment]
Glad to hear it!
